# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protocol.proto',
  package='insigma_communication',
  serialized_pb='\n\x0eprotocol.proto\x12\x15insigma_communication\"\xc9\x01\n\x04\x42lur\x12\x11\n\tintensity\x18\x01 \x01(\x05\x12\x1e\n\x16reconstruction_quality\x18\x02 \x01(\x02\x12\x1a\n\x12watermark_strength\x18\x03 \x01(\x02\x12\x33\n\x07regions\x18\x04 \x03(\x0b\x32\".insigma_communication.Blur.Region\x1a=\n\x06Region\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\"k\n\x06\x44\x65tect\x12\x37\n\x08\x63\x61scades\x18\x01 \x03(\x0e\x32%.insigma_communication.Detect.Cascade\"(\n\x07\x43\x61scade\x12\t\n\x05\x46RONT\x10\x00\x12\x08\n\x04SIDE\x10\x01\x12\x08\n\x04\x45YES\x10\x02\"{\n\tRecognize\x12\x38\n\x07regions\x18\x01 \x03(\x0b\x32\'.insigma_communication.Recognize.Region\x1a\x34\n\x06Region\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\x12\t\n\x01\x63\x18\x03 \x01(\x05\x12\t\n\x01\x64\x18\x04 \x01(\x05\"\x95\x01\n\x04Task\x12-\n\x06\x64\x65tect\x18\x01 \x01(\x0b\x32\x1d.insigma_communication.Detect\x12\x33\n\trecognize\x18\x02 \x01(\x0b\x32 .insigma_communication.Recognize\x12)\n\x04\x62lur\x18\x03 \x01(\x0b\x32\x1b.insigma_communication.Blur')



_DETECT_CASCADE = descriptor.EnumDescriptor(
  name='Cascade',
  full_name='insigma_communication.Detect.Cascade',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='FRONT', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SIDE', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EYES', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=312,
  serialized_end=352,
)


_BLUR_REGION = descriptor.Descriptor(
  name='Region',
  full_name='insigma_communication.Blur.Region',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='x', full_name='insigma_communication.Blur.Region.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y', full_name='insigma_communication.Blur.Region.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='width', full_name='insigma_communication.Blur.Region.width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='height', full_name='insigma_communication.Blur.Region.height', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=182,
  serialized_end=243,
)

_BLUR = descriptor.Descriptor(
  name='Blur',
  full_name='insigma_communication.Blur',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='intensity', full_name='insigma_communication.Blur.intensity', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reconstruction_quality', full_name='insigma_communication.Blur.reconstruction_quality', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='watermark_strength', full_name='insigma_communication.Blur.watermark_strength', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='regions', full_name='insigma_communication.Blur.regions', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_BLUR_REGION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=42,
  serialized_end=243,
)


_DETECT = descriptor.Descriptor(
  name='Detect',
  full_name='insigma_communication.Detect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='cascades', full_name='insigma_communication.Detect.cascades', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DETECT_CASCADE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=245,
  serialized_end=352,
)


_RECOGNIZE_REGION = descriptor.Descriptor(
  name='Region',
  full_name='insigma_communication.Recognize.Region',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='a', full_name='insigma_communication.Recognize.Region.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='b', full_name='insigma_communication.Recognize.Region.b', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='c', full_name='insigma_communication.Recognize.Region.c', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='d', full_name='insigma_communication.Recognize.Region.d', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=425,
  serialized_end=477,
)

_RECOGNIZE = descriptor.Descriptor(
  name='Recognize',
  full_name='insigma_communication.Recognize',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='regions', full_name='insigma_communication.Recognize.regions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RECOGNIZE_REGION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=354,
  serialized_end=477,
)


_TASK = descriptor.Descriptor(
  name='Task',
  full_name='insigma_communication.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='detect', full_name='insigma_communication.Task.detect', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='recognize', full_name='insigma_communication.Task.recognize', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='blur', full_name='insigma_communication.Task.blur', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=480,
  serialized_end=629,
)

_BLUR_REGION.containing_type = _BLUR;
_BLUR.fields_by_name['regions'].message_type = _BLUR_REGION
_DETECT.fields_by_name['cascades'].enum_type = _DETECT_CASCADE
_DETECT_CASCADE.containing_type = _DETECT;
_RECOGNIZE_REGION.containing_type = _RECOGNIZE;
_RECOGNIZE.fields_by_name['regions'].message_type = _RECOGNIZE_REGION
_TASK.fields_by_name['detect'].message_type = _DETECT
_TASK.fields_by_name['recognize'].message_type = _RECOGNIZE
_TASK.fields_by_name['blur'].message_type = _BLUR
DESCRIPTOR.message_types_by_name['Blur'] = _BLUR
DESCRIPTOR.message_types_by_name['Detect'] = _DETECT
DESCRIPTOR.message_types_by_name['Recognize'] = _RECOGNIZE
DESCRIPTOR.message_types_by_name['Task'] = _TASK

class Blur(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Region(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _BLUR_REGION
    
    # @@protoc_insertion_point(class_scope:insigma_communication.Blur.Region)
  DESCRIPTOR = _BLUR
  
  # @@protoc_insertion_point(class_scope:insigma_communication.Blur)

class Detect(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DETECT
  
  # @@protoc_insertion_point(class_scope:insigma_communication.Detect)

class Recognize(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Region(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _RECOGNIZE_REGION
    
    # @@protoc_insertion_point(class_scope:insigma_communication.Recognize.Region)
  DESCRIPTOR = _RECOGNIZE
  
  # @@protoc_insertion_point(class_scope:insigma_communication.Recognize)

class Task(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TASK
  
  # @@protoc_insertion_point(class_scope:insigma_communication.Task)

# @@protoc_insertion_point(module_scope)
